version: '3.3'

services:
  apache:
    build:
      context: .
    container_name: apache
    volumes:
      - './:/var/www/html'
    env_file:
      - ./.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.apache.rule=Host(`${BASE_URL}`)"
      - "traefik.http.services.apache.loadbalancer.server.port=80"
  
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    volumes:
      - './mysql_db:/var/lib/mysql'
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  phpmyadmin:
    image: phpmyadmin:5
    container_name: phpmyadmin
    restart: always
    links:
      - db
    environment:
      - PMA_HOST=${PMA_HOST}
      - PMA_PORT=${PMA_PORT}
      - PMA_ARBITRARY=${PMA_ARBITRARY}
    labels:
      - "traefik.http.routers.phpmyadmin.rule=Host(`pma.localhost`)"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"


  traefik:
    image: traefik:v2.6
    container_name: "traefik"
    command:
    - --log.level=INFO
    - --api.insecure=true
    - --entrypoints.web.address=:80
    - --providers.docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "8080:8080"
      - "80:80"